// Generated by CoffeeScript 1.7.1
(function() {
  var scrollOff, scrollTo;

  scrollOff = $('#nav-top').height();

  scrollTo = function(target, ms, cb) {
    if (ms == null) {
      ms = 250;
    }
    return $('html, body').animate({
      scrollTop: $(target).offset().top - scrollOff
    }, ms, 'swing', ((cb != null) && typeof cb === 'function' ? cb : null));
  };

  $('.link-scroll').on('click', function(e) {
    var target;
    e.preventDefault();
    e.stopPropagation();
    target = $(this).attr('href');
    if (target === '#') {
      target = 'body';
    }
    return scrollTo(target, 250, function() {
      $('[data-toggle="dropdown"]').parent().removeClass('open');
      return $('#nav-top-collapse').collapse('toggle');
    });
  });

}).call(this);

//# sourceMappingURL=app.map
