// Generated by CoffeeScript 1.7.1
(function() {
  var chevron, dropdown, navCollapse, scrollOff, scrollTo;

  navCollapse = $('#nav-top-collapse');

  dropdown = $('[data-toggle="dropdown"]');

  chevron = dropdown.children('span');

  scrollOff = $('#nav-top').height();

  scrollTo = function(target, ms, cb) {
    if (ms == null) {
      ms = 250;
    }
    return $('html, body').animate({
      scrollTop: $(target).offset().top - scrollOff
    }, ms, 'swing', ((cb != null) && typeof cb === 'function' ? cb : null));
  };

  dropdown.on('click', function(e) {
    if (dropdown.parent().hasClass('open')) {
      return chevron.removeClass('octicon-chevron-up').addClass('octicon-chevron-down');
    } else {
      return chevron.removeClass('octicon-chevron-down').addClass('octicon-chevron-up');
    }
  });

  $('.link-scroll').on('click', function(e) {
    var target;
    e.preventDefault();
    e.stopPropagation();
    target = $(this).attr('href');
    if (target === '#') {
      target = 'body';
    }
    return scrollTo(target, 250, function() {
      dropdown.parent().removeClass('open');
      dropdown.children('span').removeClass('octicon-chevron-up').addClass('octicon-chevron-down');
      if (navCollapse.hasClass('in')) {
        return navCollapse.collapse('toggle');
      }
    });
  });

}).call(this);

//# sourceMappingURL=app.map
