// Generated by CoffeeScript 1.7.1
(function() {
  var chevron, dropdown, gallery, navCollapse, scrollOff, scrollTo;

  navCollapse = $('#nav-top-collapse');

  dropdown = $('[data-toggle="dropdown"]');

  chevron = dropdown.children('.octicon');

  gallery = $('.list-gallery');

  scrollOff = $('#nav-top').height();

  scrollTo = function(target, ms, cb) {
    if (ms == null) {
      ms = 250;
    }
    return $('html, body').animate({
      scrollTop: $(target).offset().top - scrollOff
    }, ms, 'swing', ((cb != null) && typeof cb === 'function' ? cb : null));
  };

  $('.link-scroll').on('click', function(e) {
    var target;
    e.preventDefault();
    e.stopPropagation();
    target = $(this).attr('href');
    if (target === '#') {
      target = 'body';
    }
    return scrollTo(target, 250, function() {
      dropdown.parent().removeClass('open');
      if (navCollapse.hasClass('in')) {
        return navCollapse.collapse('toggle');
      }
    });
  });

  dropdown.on('focusin', function(e) {
    return chevron.removeClass('octicon-chevron-down').addClass('octicon-chevron-up');
  });

  dropdown.on('focusout', function(e) {
    return chevron.removeClass('octicon-chevron-up').addClass('octicon-chevron-down');
  });

  gallery.each(function() {
    return $(this).magnificPopup({
      delegate: 'a',
      type: 'image',
      tLoading: 'loading image #%curr%...',
      image: {
        verticalFit: true
      },
      gallery: {
        enabled: true,
        preload: [1, 1]
      }
    });
  });

}).call(this);

//# sourceMappingURL=app.map
